apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cloud-native-app
  name: cloud-native-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-native-app
      name: cloud-native-app
    spec:
      containers:
        - name: cloud-native-app
          image: "gcr.io/hightowerlabs/cloud-native-app:8afea5b5-fa2b-4119-9473-6524225a8d2e" 
          imagePullPolicy: Always
          env:
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cloud-native-app
                  key: database
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - "-tls-cert=/etc/tls/tls.crt"
            - "-tls-key=/etc/tls/tls.key"
            - "-database=$(DATABASE)"
          volumeMounts:
            - name: "service-account"
              mountPath: "/var/run/secret/cloud.google.com"
            - name: "certs"
              mountPath: "/etc/ssl/certs"
            - name: "tls"
              mountPath: "/etc/tls"
      volumes:
        - name: "tls"
          secret:
            secretName: cloud-native-app-tls
        - name: "service-account"
          secret:
            secretName: cloud-native-app
        - name: "certs"
          hostPath:
            path: "/etc/ssl/certs"
