steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=cloud-native-app"]
    args: ["install", "."]
    id: "go-install"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/cloud-native-app:${BUILD_ID}", "."]
    id: "docker-build"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/cloud-native-app:${BUILD_ID}"]
    id: "docker-push"

  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "gs://${PROJECT_ID}/k0-kubeconfig", "/workspace/kubeconfig"]
    waitFor: ["-"]
    id: "get-kubeconfig" 
 
  - name: "gcr.io/google_containers/hyperkube:v1.5.3"
    env: ["KUBECONFIG=/workspace/kubeconfig"]
    entrypoint: "/hyperkube"
    args: ["kubectl", "set", "image", "-f", "/workspace/deployments/cna.yaml",
           "cloud-native-app=gcr.io/${PROJECT_ID}/cloud-native-app:${BUILD_ID}",
           "--local", "-o", "yaml"]
    waitFor: ["get-kubeconfig", "docker-push"]
