steps:
  - name: 'gcr.io/cloud-builders/go'
    env: ['PROJECT_ROOT=cloud-native-app']
    args: ['install', '.']
    id: 'go-install'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-native-app:$BUILD_ID', '.']

images: ['gcr.io/$PROJECT_ID/cloud-native-app:$BUILD_ID']
